apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress-container
          image: wordpress-img
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: lb-wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050
  selector:
    app: wordpress